// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package durudexv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// EmailServiceClient is the client API for EmailService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EmailServiceClient interface {
	// Sending an email to a user with a verification code.
	SendEmailUserCode(ctx context.Context, in *SendEmailUserCodeRequest, opts ...grpc.CallOption) (*SendEmailUserCodeResponse, error)
	// Sending an email to a user with logged in.
	SendEmailUserLoggedIn(ctx context.Context, in *SendEmailUserLoggedInRequest, opts ...grpc.CallOption) (*SendEmailUserLoggedInResponse, error)
	// Sending an email to a user with register.
	SendEmailUserRegister(ctx context.Context, in *SendEmailUserRegisterRequest, opts ...grpc.CallOption) (*SendEmailUserRegisterResponse, error)
}

type emailServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEmailServiceClient(cc grpc.ClientConnInterface) EmailServiceClient {
	return &emailServiceClient{cc}
}

func (c *emailServiceClient) SendEmailUserCode(ctx context.Context, in *SendEmailUserCodeRequest, opts ...grpc.CallOption) (*SendEmailUserCodeResponse, error) {
	out := new(SendEmailUserCodeResponse)
	err := c.cc.Invoke(ctx, "/durudex.v1.EmailService/SendEmailUserCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailServiceClient) SendEmailUserLoggedIn(ctx context.Context, in *SendEmailUserLoggedInRequest, opts ...grpc.CallOption) (*SendEmailUserLoggedInResponse, error) {
	out := new(SendEmailUserLoggedInResponse)
	err := c.cc.Invoke(ctx, "/durudex.v1.EmailService/SendEmailUserLoggedIn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailServiceClient) SendEmailUserRegister(ctx context.Context, in *SendEmailUserRegisterRequest, opts ...grpc.CallOption) (*SendEmailUserRegisterResponse, error) {
	out := new(SendEmailUserRegisterResponse)
	err := c.cc.Invoke(ctx, "/durudex.v1.EmailService/SendEmailUserRegister", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmailServiceServer is the server API for EmailService service.
// All implementations must embed UnimplementedEmailServiceServer
// for forward compatibility
type EmailServiceServer interface {
	// Sending an email to a user with a verification code.
	SendEmailUserCode(context.Context, *SendEmailUserCodeRequest) (*SendEmailUserCodeResponse, error)
	// Sending an email to a user with logged in.
	SendEmailUserLoggedIn(context.Context, *SendEmailUserLoggedInRequest) (*SendEmailUserLoggedInResponse, error)
	// Sending an email to a user with register.
	SendEmailUserRegister(context.Context, *SendEmailUserRegisterRequest) (*SendEmailUserRegisterResponse, error)
	mustEmbedUnimplementedEmailServiceServer()
}

// UnimplementedEmailServiceServer must be embedded to have forward compatible implementations.
type UnimplementedEmailServiceServer struct {
}

func (UnimplementedEmailServiceServer) SendEmailUserCode(context.Context, *SendEmailUserCodeRequest) (*SendEmailUserCodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendEmailUserCode not implemented")
}
func (UnimplementedEmailServiceServer) SendEmailUserLoggedIn(context.Context, *SendEmailUserLoggedInRequest) (*SendEmailUserLoggedInResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendEmailUserLoggedIn not implemented")
}
func (UnimplementedEmailServiceServer) SendEmailUserRegister(context.Context, *SendEmailUserRegisterRequest) (*SendEmailUserRegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendEmailUserRegister not implemented")
}
func (UnimplementedEmailServiceServer) mustEmbedUnimplementedEmailServiceServer() {}

// UnsafeEmailServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EmailServiceServer will
// result in compilation errors.
type UnsafeEmailServiceServer interface {
	mustEmbedUnimplementedEmailServiceServer()
}

func RegisterEmailServiceServer(s grpc.ServiceRegistrar, srv EmailServiceServer) {
	s.RegisterService(&EmailService_ServiceDesc, srv)
}

func _EmailService_SendEmailUserCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendEmailUserCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailServiceServer).SendEmailUserCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/durudex.v1.EmailService/SendEmailUserCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailServiceServer).SendEmailUserCode(ctx, req.(*SendEmailUserCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmailService_SendEmailUserLoggedIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendEmailUserLoggedInRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailServiceServer).SendEmailUserLoggedIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/durudex.v1.EmailService/SendEmailUserLoggedIn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailServiceServer).SendEmailUserLoggedIn(ctx, req.(*SendEmailUserLoggedInRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmailService_SendEmailUserRegister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendEmailUserRegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailServiceServer).SendEmailUserRegister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/durudex.v1.EmailService/SendEmailUserRegister",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailServiceServer).SendEmailUserRegister(ctx, req.(*SendEmailUserRegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EmailService_ServiceDesc is the grpc.ServiceDesc for EmailService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EmailService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "durudex.v1.EmailService",
	HandlerType: (*EmailServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendEmailUserCode",
			Handler:    _EmailService_SendEmailUserCode_Handler,
		},
		{
			MethodName: "SendEmailUserLoggedIn",
			Handler:    _EmailService_SendEmailUserLoggedIn_Handler,
		},
		{
			MethodName: "SendEmailUserRegister",
			Handler:    _EmailService_SendEmailUserRegister_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "durudex/v1/email.proto",
}
